name: "GoSungrow"
description: "Fetch data from isolarcloud.com and push to HA."
version: "3.0.0"
stage: stable
slug: "gosungrow"
url: "https://github.com/MickMake/GoSunGrow/"
codenotary: mick@mickmake.com
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
map:
  - config:rw
panel_icon: mdi:solar-power
auth_api: true
startup: services
hassio_api: true
init: false

options:
  message: "GoSungrow config"
  sungrow:
    - user: ""
      password: ""
    - host: "https://augateway.isolarcloud.com"
    - appkey: "93D72E60331ABDCDC7B39ADC2D1F32B3"
  mqtt:
    - host: ""
      port: ""
    - user: ""
      password: ""
  debug: false
  timeout: 60
schema:
  sungrow:
    - user: str
      password: password
    - host: str?
    - appkey: str?
  mqtt:
    - host: str?
      port: str?
    - user: str?
      password: password?
  debug: bool?
  timeout: int?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
